// Automatically generated by sapi_cc_embed_data() Bazel rule

#ifndef SANDBOXED_API_FILE_TOC_H_
#define SANDBOXED_API_FILE_TOC_H_

#include <cstddef>

struct FileToc {
  const char* name;
  const char* data;
  size_t size;
  // Not actually used/computed by sapi_cc_embed_data(), this is for
  // compatibility with legacy code.
  unsigned char md5digest[16];
};

#endif  // SANDBOXED_API_FILE_TOC_H_

#ifndef sandboxed_api_sandbox2_examples_openinjector_tester_sapi_embed_H_
#define sandboxed_api_sandbox2_examples_openinjector_tester_sapi_embed_H_


const FileToc* tester_sapi_embed_create();
size_t tester_sapi_embed_size();

#endif  // sandboxed_api_sandbox2_examples_openinjector_tester_sapi_embed_H_
