// AUTO-GENERATED by the Sandboxed API generator.
// Edits will be discarded when regenerating this file.

#ifndef TESTER_SAPI_SAPI_H_
#define TESTER_SAPI_SAPI_H_
#include "sandboxed_api/sandbox.h"
#include "sandboxed_api/vars.h"
#include "/home/vincenzo/Coding/sandboxed-api-20190823/sandboxed_api/sandbox2/examples/openinjector/tester-sapi_embed.h"

class TesterSandbox : public ::sapi::Sandbox {
 public:
  TesterSandbox() : ::sapi::Sandbox(tester_sapi_embed_create()) {}
};
class TesterApi {
 public:
  explicit TesterApi(::sapi::Sandbox* sandbox) : sandbox_(sandbox) {}
  // Deprecated
  ::sapi::Sandbox* GetSandbox() const { return sandbox(); }
  ::sapi::Sandbox* sandbox() const { return sandbox_; }

 private:
  ::sapi::Sandbox* sandbox_;
};

#endif  // TESTER_SAPI_SAPI_H_
